In [1]:
import numpy as np


In [29]:
np.zeros((5), dtype=int)

array([0, 0, 0, 0, 0])

In [18]:
arr = np.zeros((1,1,3,5))

In [9]:
np.ones((((2,3))))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
arr.shape

(1, 1, 3, 5)

In [20]:
arr

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [31]:
np.eye(2,3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0]])

In [42]:
np.empty((3,3), dtype=int)

array([[         0,          0, -143491888],
       [       317, -143489728,        317],
       [-143491568,        317,        108]])

In [45]:
np.zeros(3)

array([0., 0., 0.])

In [52]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [53]:
np.ones(3, dtype=int)

array([1, 1, 1])

In [55]:
np.ones((1,1,1,2,3), dtype=int)

array([[[[[1, 1, 1],
          [1, 1, 1]]]]])

In [56]:
arr = np.ones((3,4), dtype=int)

In [57]:
arr+5

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [58]:
arr*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [63]:
arr = arr+1

In [64]:
arr

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [65]:
arr.ndim

2

In [72]:
arr = np.ones((1,1,2,3), dtype = int)

In [73]:
arr

array([[[[1, 1, 1],
         [1, 1, 1]]]])

In [74]:
arr.ndim

4

In [80]:
np.eye(4, dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [86]:
np.empty((3,2))

array([[2.12199579e-314, 2.12199579e-314],
       [2.12199579e-314, 2.12199579e-314],
       [2.12199579e-314, 2.12199579e-314]])

In [1]:
import random

In [4]:
random.choice('mahaj')

'a'

In [5]:
random.uniform(7,14)

7.019257404144929

In [9]:
import numpy as np
np.random.random_sample(5)

array([0.72401324, 0.73845229, 0.45233286, 0.47505436, 0.42630712])

In [18]:
arr = np.random.randint(1,5, size=(3,4))

In [19]:
arr

array([[4, 4, 1, 2],
       [3, 4, 1, 3],
       [3, 1, 4, 4]])

In [25]:
arr1 = arr.reshape(6,2)

In [26]:
arr1

array([[4, 4],
       [1, 2],
       [3, 4],
       [1, 3],
       [3, 1],
       [4, 4]])

In [27]:
arr

array([[4, 4, 1, 2],
       [3, 4, 1, 3],
       [3, 1, 4, 4]])

In [40]:
arr.reshape(1,2,2,3)

array([[[[4, 4, 1],
         [2, 3, 4]]],


       [[[1, 3, 3],
         [1, 4, 4]]]])

In [1]:
import numpy as np

In [2]:
import random

In [9]:
np.random.random_sample()

0.5098546547707143

In [15]:
np.random.random_sample((2,3))

array([[0.93303108, 0.67617926, 0.53765376],
       [0.70192474, 0.46768362, 0.87846144]])

In [21]:
np.random.rand(2,3)

array([[0.03752515, 0.17185684, 0.74728022],
       [0.6515108 , 0.30295888, 0.36806532]])

In [23]:
np.random.random()

0.9967785437817217

In [25]:
np.random.randn(2,3)

array([[-0.51547671,  0.41494921,  0.21977452],
       [ 0.10988665, -0.52052412, -0.0905687 ]])

In [35]:
np.random.randint(1,6,size=(4,4))

array([[1, 3, 3, 5],
       [1, 3, 2, 2],
       [3, 4, 2, 1],
       [2, 1, 3, 3]])

In [41]:
np.random.randint(1,10 ,(3,3))

array([[7, 2, 1],
       [1, 3, 3],
       [7, 8, 2]])

In [55]:
arr1 = np.random.randint(1,10, (5,6))

In [56]:
arr1

array([[8, 1, 8, 3, 1, 5],
       [6, 4, 7, 4, 8, 2],
       [3, 1, 3, 8, 1, 1],
       [7, 4, 4, 9, 9, 2],
       [1, 6, 7, 4, 6, 8]])

In [57]:
arr1.shape

(5, 6)

In [58]:
arr1.size

30

In [59]:
arr1.ndim

2

In [60]:
type(arr1)

numpy.ndarray

In [61]:
arr1

array([[8, 1, 8, 3, 1, 5],
       [6, 4, 7, 4, 8, 2],
       [3, 1, 3, 8, 1, 1],
       [7, 4, 4, 9, 9, 2],
       [1, 6, 7, 4, 6, 8]])

In [62]:
arr1>3

array([[ True, False,  True, False, False,  True],
       [ True,  True,  True,  True,  True, False],
       [False, False, False,  True, False, False],
       [ True,  True,  True,  True,  True, False],
       [False,  True,  True,  True,  True,  True]])

In [63]:
arr1<3

array([[False,  True, False, False,  True, False],
       [False, False, False, False, False,  True],
       [False,  True, False, False,  True,  True],
       [False, False, False, False, False,  True],
       [ True, False, False, False, False, False]])

In [64]:
arr1[arr1>3]

array([8, 8, 5, 6, 4, 7, 4, 8, 8, 7, 4, 4, 9, 9, 6, 7, 4, 6, 8])

In [65]:
arr1

array([[8, 1, 8, 3, 1, 5],
       [6, 4, 7, 4, 8, 2],
       [3, 1, 3, 8, 1, 1],
       [7, 4, 4, 9, 9, 2],
       [1, 6, 7, 4, 6, 8]])

In [66]:
arr1[arr1<3]

array([1, 1, 2, 1, 1, 1, 2, 1])

In [67]:
arr1[0]

array([8, 1, 8, 3, 1, 5])

In [70]:
arr1[1]

array([6, 4, 7, 4, 8, 2])

In [72]:
arr1[1][4]

8

In [73]:
arr1

array([[8, 1, 8, 3, 1, 5],
       [6, 4, 7, 4, 8, 2],
       [3, 1, 3, 8, 1, 1],
       [7, 4, 4, 9, 9, 2],
       [1, 6, 7, 4, 6, 8]])

In [74]:
arr1[0:3]

array([[8, 1, 8, 3, 1, 5],
       [6, 4, 7, 4, 8, 2],
       [3, 1, 3, 8, 1, 1]])

In [77]:
arr1[3:5]

array([[7, 4, 4, 9, 9, 2],
       [1, 6, 7, 4, 6, 8]])

In [79]:
arr1[0:3]

array([[8, 1, 8, 3, 1, 5],
       [6, 4, 7, 4, 8, 2],
       [3, 1, 3, 8, 1, 1]])

In [80]:
arr1[0:3, 3:5]

array([[3, 1],
       [4, 8],
       [8, 1]])

In [84]:
arr1[0:2, [0,5]]

array([[8, 5],
       [6, 2]])

In [86]:
arr1 = np.random.randint(1,3,(3,3))

In [87]:
arr2 = np.random.randint(1,3,(3,3))

In [88]:
arr1+arr2

array([[3, 4, 4],
       [4, 3, 3],
       [3, 3, 4]])

In [89]:
arr1

array([[1, 2, 2],
       [2, 1, 2],
       [2, 1, 2]])

In [90]:
arr2

array([[2, 2, 2],
       [2, 2, 1],
       [1, 2, 2]])

In [91]:
arr1+arr2

array([[3, 4, 4],
       [4, 3, 3],
       [3, 3, 4]])

In [92]:
arr1 - arr2

array([[-1,  0,  0],
       [ 0, -1,  1],
       [ 1, -1,  0]])

In [93]:
arr2-arr1

array([[ 1,  0,  0],
       [ 0,  1, -1],
       [-1,  1,  0]])

In [96]:
arr1, arr2

(array([[1, 2, 2],
        [2, 1, 2],
        [2, 1, 2]]),
 array([[2, 2, 2],
        [2, 2, 1],
        [1, 2, 2]]))

In [97]:
arr1*arr2

array([[2, 4, 4],
       [4, 2, 2],
       [2, 2, 4]])

In [98]:
arr1 / arr2

array([[0.5, 1. , 1. ],
       [1. , 0.5, 2. ],
       [2. , 0.5, 1. ]])

In [99]:
arr2 / arr1

array([[2. , 1. , 1. ],
       [1. , 2. , 0.5],
       [0.5, 2. , 1. ]])

In [103]:
arr1@arr2

array([[ 8, 10,  8],
       [ 8, 10,  9],
       [ 8, 10,  9]])

In [104]:
arr1,arr2

(array([[1, 2, 2],
        [2, 1, 2],
        [2, 1, 2]]),
 array([[2, 2, 2],
        [2, 2, 1],
        [1, 2, 2]]))

In [105]:
arr1@arr2

array([[ 8, 10,  8],
       [ 8, 10,  9],
       [ 8, 10,  9]])

In [106]:
np.dot(arr1,arr2)

array([[ 8, 10,  8],
       [ 8, 10,  9],
       [ 8, 10,  9]])

In [107]:
np.dot(arr2,arr1)

array([[10,  8, 12],
       [ 8,  7, 10],
       [ 9,  6, 10]])

In [108]:
arr1

array([[1, 2, 2],
       [2, 1, 2],
       [2, 1, 2]])

In [109]:
4/0

ZeroDivisionError: division by zero

In [110]:
arr1/0

C:\Users\Dell\AppData\Local\Temp\ipykernel_518620\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [111]:
arr = np.zeros((3,3))

In [112]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [113]:
arr+5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [114]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [115]:
arr+[1,2,3]

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [116]:
arr.T

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [117]:
arr = arr+5

In [118]:
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [120]:
arr1

array([[1, 2, 2],
       [2, 1, 2],
       [2, 1, 2]])

In [121]:
arr1.T

array([[1, 2, 2],
       [2, 1, 1],
       [2, 2, 2]])

In [122]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.41421356],
       [1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.        , 1.41421356]])

In [123]:
np.exp(arr1)

array([[2.71828183, 7.3890561 , 7.3890561 ],
       [7.3890561 , 2.71828183, 7.3890561 ],
       [7.3890561 , 2.71828183, 7.3890561 ]])

In [124]:
np.log10(arr1)

array([[0.     , 0.30103, 0.30103],
       [0.30103, 0.     , 0.30103],
       [0.30103, 0.     , 0.30103]])

In [128]:
np.max(arr1)

2