In [3]:
import numpy as np

In [3]:
arr1 = np.random.randint(1,3,(3,3))

In [4]:
arr1

array([[2, 1, 1],
       [1, 1, 2],
       [1, 2, 1]])

In [5]:
arr2 = np.random.randint(1,3,(3,3))

In [6]:
arr2

array([[2, 1, 1],
       [2, 1, 2],
       [2, 2, 2]])

In [7]:
arr1

array([[2, 1, 1],
       [1, 1, 2],
       [1, 2, 1]])

In [8]:
arr1.ndim

2

In [10]:
arr1.shape, arr1.size, type(arr1), arr1.ndim

((3, 3), 9, numpy.ndarray, 2)

In [11]:
arr1.flatten()

array([2, 1, 1, 1, 1, 2, 1, 2, 1])

In [12]:
arr2

array([[2, 1, 1],
       [2, 1, 2],
       [2, 2, 2]])

In [13]:
arr2.flatten()

array([2, 1, 1, 2, 1, 2, 2, 2, 2])

In [18]:
arr = np.array([[[[1,2,3]],[[1,2,3]]]])

In [19]:
arr

array([[[[1, 2, 3]],

        [[1, 2, 3]]]])

In [20]:
arr.flatten()

array([1, 2, 3, 1, 2, 3])

In [21]:
arr = np.array([1,2,3,4])

In [23]:
arr

array([1, 2, 3, 4])

In [24]:
arr.ndim

1

In [26]:
np.expand_dims(arr, axis=0)

array([[1, 2, 3, 4]])

In [27]:
arr

array([1, 2, 3, 4])

In [28]:
np.expand_dims(arr, axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [29]:
arr = np.random.randint(1,10,(3,3))

In [30]:
arr

array([[1, 7, 8],
       [5, 3, 2],
       [4, 8, 2]])

In [32]:
np.expand_dims(arr, axis=0)

array([[[1, 7, 8],
        [5, 3, 2],
        [4, 8, 2]]])

In [33]:
np.expand_dims(arr, axis=1)

array([[[1, 7, 8]],

       [[5, 3, 2]],

       [[4, 8, 2]]])

In [34]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [36]:
np.expand_dims(arr, axis=0)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [37]:
np.expand_dims(arr,axis=1)

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [43]:
arr = np.random.randint(1,10,(1,1,3,4))

In [44]:
arr

array([[[[2, 1, 6, 2],
         [9, 8, 8, 7],
         [5, 9, 9, 3]]]])

In [45]:
np.squeeze(arr)

array([[2, 1, 6, 2],
       [9, 8, 8, 7],
       [5, 9, 9, 3]])

In [53]:
a = np.array([[[1,2,3,4]]])

In [54]:
a

array([[[1, 2, 3, 4]]])

In [55]:
np.squeeze(a)

array([1, 2, 3, 4])

In [62]:
a = np.array([[[[1,2]],[[3,4]]]])

In [63]:
a

array([[[[1, 2]],

        [[3, 4]]]])

In [64]:
np.squeeze(a)

array([[1, 2],
       [3, 4]])

In [65]:
a

array([[[[1, 2]],

        [[3, 4]]]])

In [68]:
arr = np.array([1,2,3,4])

In [70]:
np.repeat(arr,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [73]:
np.repeat(arr, 3,axis=0)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [74]:
arr = np.random.randint(1,10,(3,4))

In [75]:
arr

array([[5, 3, 3, 7],
       [4, 2, 3, 1],
       [8, 9, 9, 9]])

In [76]:
np.repeat(arr, 2)

array([5, 5, 3, 3, 3, 3, 7, 7, 4, 4, 2, 2, 3, 3, 1, 1, 8, 8, 9, 9, 9, 9,
       9, 9])

In [77]:
np.repeat(arr, 2, axis=0)

array([[5, 3, 3, 7],
       [5, 3, 3, 7],
       [4, 2, 3, 1],
       [4, 2, 3, 1],
       [8, 9, 9, 9],
       [8, 9, 9, 9]])

In [79]:
np.repeat(arr,3,axis=1)

array([[5, 5, 5, 3, 3, 3, 3, 3, 3, 7, 7, 7],
       [4, 4, 4, 2, 2, 2, 3, 3, 3, 1, 1, 1],
       [8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [80]:
arr =np.array([1,2,3,4])

In [82]:
arr

array([1, 2, 3, 4])

In [83]:
np.roll(arr,-1)

array([2, 3, 4, 1])

In [84]:
np.roll(arr,-3)

array([4, 1, 2, 3])

In [86]:
np.roll(arr,3)

array([2, 3, 4, 1])

In [4]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
np.roll(arr,-3)

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [95]:
np.roll(arr,-2)

array([[3, 4, 5],
       [6, 7, 8],
       [9, 1, 2]])

In [98]:
np.roll(arr,-1,axis=0)

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [111]:
np.roll(arr,-1,axis=1)

array([[2, 3, 1],
       [5, 6, 4],
       [8, 9, 7]])

In [112]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [8]:
arr1

array([[1, 2, 1],
       [2, 1, 2],
       [2, 2, 2]])

In [9]:
arr2

array([[1, 1, 2],
       [1, 1, 1],
       [2, 2, 1]])

In [10]:
arr1>arr2

array([[False,  True, False],
       [ True, False,  True],
       [False, False,  True]])

In [12]:
arr2 == arr1

array([[ True, False, False],
       [False,  True, False],
       [ True,  True, False]])

In [13]:
arr1!=arr2

array([[False,  True,  True],
       [ True, False,  True],
       [False, False,  True]])

In [14]:
arr1,arr2

(array([[1, 2, 1],
        [2, 1, 2],
        [2, 2, 2]]),
 array([[1, 1, 2],
        [1, 1, 1],
        [2, 2, 1]]))

In [23]:
arr = np.array(["My pw","skills"])

In [24]:
arr

array(['My pw', 'skills'], dtype='<U6')

In [25]:
np.char.upper(arr)

array(['MY PW', 'SKILLS'], dtype='<U6')

In [26]:
np.char.lower(arr)

array(['my pw', 'skills'], dtype='<U6')

In [27]:
np.char.title(arr)

array(['My Pw', 'Skills'], dtype='<U6')

In [28]:
np.char.capitalize(arr)

array(['My pw', 'Skills'], dtype='<U6')

In [29]:
arr1

array([[1, 2, 1],
       [2, 1, 2],
       [2, 2, 2]])

In [30]:
np.sin(arr1)

array([[0.84147098, 0.90929743, 0.84147098],
       [0.90929743, 0.84147098, 0.90929743],
       [0.90929743, 0.90929743, 0.90929743]])

In [32]:
np.cos(arr1)

array([[ 0.54030231, -0.41614684,  0.54030231],
       [-0.41614684,  0.54030231, -0.41614684],
       [-0.41614684, -0.41614684, -0.41614684]])

In [33]:
np.tan(arr1)

array([[ 1.55740772, -2.18503986,  1.55740772],
       [-2.18503986,  1.55740772, -2.18503986],
       [-2.18503986, -2.18503986, -2.18503986]])

In [34]:
np.log10(arr1)

array([[0.     , 0.30103, 0.     ],
       [0.30103, 0.     , 0.30103],
       [0.30103, 0.30103, 0.30103]])

In [38]:
np.power(arr1, 4)

array([[ 1, 16,  1],
       [16,  1, 16],
       [16, 16, 16]], dtype=int32)

In [39]:
np.exp(arr1)

array([[2.71828183, 7.3890561 , 2.71828183],
       [7.3890561 , 2.71828183, 7.3890561 ],
       [7.3890561 , 7.3890561 , 7.3890561 ]])

In [40]:
np.mean(arr1)

1.6666666666666667

In [41]:
np.median(arr1)

2.0

In [44]:
np.max(arr1)

2

In [45]:
np.std(arr1)

0.4714045207910317

In [46]:
np.var(arr1)

0.2222222222222222

In [47]:
arr1,arr2

(array([[1, 2, 1],
        [2, 1, 2],
        [2, 2, 2]]),
 array([[1, 1, 2],
        [1, 1, 1],
        [2, 2, 1]]))

In [48]:
arr1-arr2

array([[ 0,  1, -1],
       [ 1,  0,  1],
       [ 0,  0,  1]])

In [49]:
np.subtract(arr1,arr2)

array([[ 0,  1, -1],
       [ 1,  0,  1],
       [ 0,  0,  1]])

In [50]:
arr2-arr1

array([[ 0, -1,  1],
       [-1,  0, -1],
       [ 0,  0, -1]])

In [51]:
np.subtract(arr2,arr1)

array([[ 0, -1,  1],
       [-1,  0, -1],
       [ 0,  0, -1]])

In [52]:
np.add(arr1,arr2)

array([[2, 3, 3],
       [3, 2, 3],
       [4, 4, 3]])

In [53]:
arr1+arr2

array([[2, 3, 3],
       [3, 2, 3],
       [4, 4, 3]])

In [54]:
np.mod(arr1,arr2)

array([[0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [55]:
arr1%arr2

array([[0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [56]:
arr1,arr2

(array([[1, 2, 1],
        [2, 1, 2],
        [2, 2, 2]]),
 array([[1, 1, 2],
        [1, 1, 1],
        [2, 2, 1]]))

In [57]:
np.sqrt(arr2)

array([[1.        , 1.        , 1.41421356],
       [1.        , 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.        ]])

In [58]:
np.sort(arr1)

array([[1, 1, 2],
       [1, 2, 2],
       [2, 2, 2]])

In [59]:
arr1

array([[1, 2, 1],
       [2, 1, 2],
       [2, 2, 2]])

In [60]:
arr = np.array([1,576,6,3,4,9,90])

In [61]:
np.sort(arr)

array([  1,   3,   4,   6,   9,  90, 576])

In [62]:
arr1 = np.random.randint(1,10,(3,3))

In [63]:
arr1

array([[3, 2, 7],
       [4, 5, 2],
       [8, 3, 8]])

In [67]:
np.sort(arr1)

array([[2, 3, 7],
       [2, 4, 5],
       [3, 8, 8]])

In [73]:
np.searchsorted(arr,5)

5