In [3]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [5]:
lis = [1,2,3,"pwskills",8.7]

In [6]:
type(lis)

list

In [16]:
#numpy stores the data in an array
l = [1,2,3,4.1]

In [17]:
arr = np.array(l)

In [18]:
arr

array([1. , 2. , 3. , 4.1])

In [19]:
l1 = [1,2,3,"mahak"]

In [20]:
arr = np.array(l1)

In [21]:
arr

array(['1', '2', '3', 'mahak'], dtype='<U11')

In [22]:
len(arr)

4

In [26]:
arr[3]

'mahak'

In [27]:
type(arr)

numpy.ndarray

In [36]:
arr1 = np.array([[1,2,3],[3,4,5]])

In [37]:
arr1

array([[1, 2, 3],
       [3, 4, 5]])

In [34]:
arr1.ndim

2

In [38]:
mat = np.matrix([1,2,3,4])

In [39]:
type(mat)

numpy.matrix

In [40]:
mat

matrix([[1, 2, 3, 4]])

In [41]:
mat.ndim

2

In [43]:
np.matrix([[[1,2,3]]])

ValueError: matrix must be 2-dimensional

In [44]:
l = [1,2,3]

In [46]:
arr = np.asarray(l)

In [47]:
arr

array([1, 2, 3])

In [48]:
type(arr)

numpy.ndarray

In [49]:
mat = np.matrix([1,2,3,4])

In [50]:
np.asarray(mat)

array([[1, 2, 3, 4]])

In [53]:
arr = np.asanyarray(mat)

In [54]:
arr

matrix([[1, 2, 3, 4]])

In [55]:
arr = np.asanyarray([1,2,3])

In [56]:
arr

array([1, 2, 3])

In [57]:
arr1 = np.asanyarray(arr)

In [58]:
arr1

array([1, 2, 3])

In [61]:
t = ((1,2,3),(2,3,4))

In [63]:
np.array(t)

array([[1, 2, 3],
       [2, 3, 4]])

In [64]:
t = ([1,2,3],[4,5,6])

In [65]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
arr = np.array([1,2,3,4])

In [67]:
arr

array([1, 2, 3, 4])

In [68]:
arr[0]

1

In [69]:
arr[0] = 300

In [70]:
arr

array([300,   2,   3,   4])

In [71]:
arr1 = arr          # shallow  copying

In [72]:
arr1

array([300,   2,   3,   4])

In [73]:
arr

array([300,   2,   3,   4])

In [74]:
arr[0]=1000

In [75]:
arr

array([1000,    2,    3,    4])

In [76]:
arr1

array([1000,    2,    3,    4])

In [77]:
#deep copying 
arr1 = arr.copy()

In [78]:
arr1

array([1000,    2,    3,    4])

In [79]:
arr

array([1000,    2,    3,    4])

In [80]:
arr[0]=9000

In [81]:
arr

array([9000,    2,    3,    4])

In [82]:
arr1

array([1000,    2,    3,    4])

In [1]:
# to create an array
# np.array
# np.asarray
# np.asanyarray
# shaallow copying and deep copying

In [7]:
arr = np.fromfunction(lambda i,j : i==j, (3,3))   

In [9]:
arr.ndim

2

In [10]:
arr

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [11]:
arr.shape

(3, 3)

In [12]:
arr2 = np.fromfunction(lambda i,j : i*j,(3,3))

In [13]:

arr2

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [15]:
for i in range(5):
    print(i)

0
1
2
3
4


In [16]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [18]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [25]:
iterable = (i for i in range(5))

In [26]:
iterable

<generator object <genexpr> at 0x00000203AC72E140>

In [27]:
np.fromiter(iterable,int)

array([0, 1, 2, 3, 4])

In [33]:
np.fromstring('2 3 4', sep=" ")

array([2., 3., 4.])

In [34]:
'mahak,dashore'.split(',')

['mahak', 'dashore']

In [35]:
np.fromstring('2,3,4', sep=",")

array([2., 3., 4.])

In [36]:
range(10)

range(0, 10)

In [44]:
np.arange(1,10,5)

array([1, 6])

In [45]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [48]:
np.logspace(1,10,5)

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [4]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [5]:
arr = np.array([1,2,3,4])

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
type(arr)

numpy.ndarray

In [18]:
l = ["mahak",1,2,3,8.9, 9+6j]

In [19]:
l

['mahak', 1, 2, 3, 8.9, (9+6j)]

In [20]:
type(l)

list

In [21]:
arr = np.array(l)

In [22]:
arr

array(['mahak', '1', '2', '3', '8.9', '(9+6j)'], dtype='<U64')

In [23]:
type(arr)

numpy.ndarray

In [36]:
arr = np.array([[1,2,3],[4,5,6],[6,7,8]])

In [37]:
arr.ndim

2

In [38]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [39]:
arr.shape

(3, 3)

In [40]:
mat = np.matrix([1,2,3])

In [41]:
mat

matrix([[1, 2, 3]])

In [42]:
arr = np.array([1,2,3])

In [43]:
arr

array([1, 2, 3])

In [44]:
mat.ndim

2

In [45]:
arr.ndim

1

In [47]:
mat = np.matrix([[1,2,3]])

In [48]:
mat

matrix([[1, 2, 3]])

In [49]:
mat.shape

(1, 3)

In [50]:
arr = np.asarray([12,3,4])

In [51]:
arr

array([12,  3,  4])

In [52]:
np.array(mat)

array([[1, 2, 3]])

In [53]:
np.asarray(mat)

array([[1, 2, 3]])

In [54]:
np.asanyarray(mat)

matrix([[1, 2, 3]])

In [56]:
np.asanyarray([1,2,3])

array([1, 2, 3])

In [59]:
np.array(((1,2,3),(2,3,4)))

array([[1, 2, 3],
       [2, 3, 4]])

In [60]:
np.asarray(((1,2,3),(2,3,4)))

array([[1, 2, 3],
       [2, 3, 4]])

In [61]:
np.asanyarray(((1,2,3),(2,3,4)))

array([[1, 2, 3],
       [2, 3, 4]])

In [62]:
np.matrix(((1,2,3),(2,3,4)))

matrix([[1, 2, 3],
        [2, 3, 4]])

In [63]:
arr = np.array([1,2,3,4])

In [64]:
arr

array([1, 2, 3, 4])

In [65]:
arr1 = arr

In [66]:
arr1

array([1, 2, 3, 4])

In [67]:
arr

array([1, 2, 3, 4])

In [68]:
arr[0] = 9000

In [69]:
arr

array([9000,    2,    3,    4])

In [70]:
arr1

array([9000,    2,    3,    4])

In [72]:
#deepcopying
arr1 = arr.copy()

In [73]:
arr[0] = 1000

In [74]:
arr

array([1000,    2,    3,    4])

In [75]:
arr1

array([9000,    2,    3,    4])

In [78]:
np.fromfunction(lambda i,j: i==j,(2,3))

array([[ True, False, False],
       [False,  True, False]])

In [79]:
np.fromfunction(lambda i,j : i*j, (4,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  2.,  4.,  6.,  8.],
       [ 0.,  3.,  6.,  9., 12.]])

In [105]:
iterable = (i for i in  range(5))

In [106]:
iterable

<generator object <genexpr> at 0x000001C1D7DDD000>

In [107]:
print(iterable)

<generator object <genexpr> at 0x000001C1D7DDD000>


In [108]:
np.fromiter(iterable,float)

array([0., 1., 2., 3., 4.])

In [109]:
np.fromstring('6 7 8',sep=" ")

array([6., 7., 8.])

In [110]:
'aj,ju,j'.split(",")

['aj', 'ju', 'j']

In [116]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [131]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])